In [2]:
!pip install mlflow

Collecting mlflow
  Using cached mlflow-3.14.0-py3-none-any.whl.metadata (49 kB)
Collecting mlflow-skinny==3.14.0 (from mlflow)
  Using cached mlflow_skinny-3.14.0-py3-none-any.whl.metadata (50 kB)
Collecting mlflow-tracing==3.14.0 (from mlflow)
  Using cached mlflow_tracing-3.14.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Using cached flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask<4 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (3.0.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (3.10.5)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (1.13.3)
Requirement already satisfied: cryptography<49,>=43.0.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (43.0.0)
Requirement already satisfied: docker<8,>=4.0.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (7.1.0)
Collecting graphene<4 (from mlflow)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: huey<4,>=2.5.4 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (3.0.3)
Requirement already satisfied: matplotlib<4 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (3.9.2)
Requirement already satisfied: numpy<3 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (1.26.4)
Requirement already satisfied: pandas<3 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<25,>=4.0.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (16.1.0)
Requirement already satisfied: scikit-learn<2 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (1.5.1)
Requirement already satisfied: scipy<2 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (1.13.1)
Requirement already satisfied: skops<1 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (2.0.34)
Requirement already satisfied: waitress<4 in c:\users\grace\anaconda3\lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<8,>=5.0.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (8.1.7)
Requirement already satisfied: cloudpickle<4 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (3.0.0)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.14.0->mlflow)
  Using cached databricks_sdk-0.119.0-py3-none-any.whl.metadata (43 kB)
Collecting fastapi<1 (from mlflow-skinny==3.14.0->mlflow)
  Using cached fastapi-0.138.1-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (3.1.43)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (7.0.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (1.43.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (1.43.0)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.14.0->mlflow)
  Using cached opentelemetry_sdk-1.43.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: packaging<27 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (24.1)
Requirement already satisfied: protobuf<8,>=3.12.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (6.33.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (0.21.0)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (6.0.1)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (2.32.3)
Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in c:\users\grace\anaconda3\lib\site-packages (from mlflow-skinny==3.14.0->mlflow) (0.49.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\grace\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\grace\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\grace\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\grace\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\grace\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\grace\anaconda3\lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.11.0)
Requirement already satisfied: Mako in c:\users\grace\anaconda3\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.2.3)
Requirement already satisfied: cffi>=1.12 in c:\users\grace\anaconda3\lib\site-packages (from cryptography<49,>=43.0.0->mlflow) (1.17.1)
Requirement already satisfied: pywin32>=304 in c:\users\grace\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (305.1)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\grace\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.2.3)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\users\grace\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\grace\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\grace\anaconda3\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in c:\users\grace\anaconda3\lib\site-packages (from Flask<4->mlflow) (1.6.2)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\users\grace\anaconda3\lib\site-packages (from graphene<4->mlflow) (3.2.11)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in c:\users\grace\anaconda3\lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\grace\anaconda3\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\grace\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\grace\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\grace\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\grace\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.4.4)
Requirement already satisfied: pillow>=8 in c:\users\grace\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\grace\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (3.1.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\grace\anaconda3\lib\site-packages (from pandas<3->mlflow) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\grace\anaconda3\lib\site-packages (from pandas<3->mlflow) (2023.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\grace\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\grace\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (3.5.0)
Requirement already satisfied: prettytable>=3.9 in c:\users\grace\anaconda3\lib\site-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\grace\anaconda3\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.0.1)
Requirement already satisfied: pycparser in c:\users\grace\anaconda3\lib\site-packages (from cffi>=1.12->cryptography<49,>=43.0.0->mlflow) (2.21)
Requirement already satisfied: colorama in c:\users\grace\anaconda3\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.14.0->mlflow) (0.4.6)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow)
  Using cached google_auth-2.55.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\grace\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.14.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\grace\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.14.0->mlflow) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\grace\anaconda3\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.14.0->mlflow) (4.0.7)
Requirement already satisfied: zipp>=0.5 in c:\users\grace\anaconda3\lib\site-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.14.0->mlflow) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\grace\anaconda3\lib\site-packages (from Jinja2>=3.1.2->Flask<4->mlflow) (2.1.3)
Requirement already satisfied: opentelemetry-semantic-conventions==0.64b0 in c:\users\grace\anaconda3\lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.14.0->mlflow) (0.64b0)
Requirement already satisfied: wcwidth>=0.3.5 in c:\users\grace\anaconda3\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\grace\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.14.0->mlflow) (0.6.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\grace\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.14.0->mlflow) (2.46.4)
Requirement already satisfied: six>=1.5 in c:\users\grace\anaconda3\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\grace\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.14.0->mlflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\grace\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.14.0->mlflow) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\grace\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.14.0->mlflow) (2025.1.31)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\grace\anaconda3\lib\site-packages (from starlette<2->mlflow-skinny==3.14.0->mlflow) (4.2.0)
Requirement already satisfied: h11>=0.8 in c:\users\grace\anaconda3\lib\site-packages (from uvicorn<1->mlflow-skinny==3.14.0->mlflow) (0.14.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\grace\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette<2->mlflow-skinny==3.14.0->mlflow) (1.3.0)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\grace\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.14.0->mlflow) (4.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\grace\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (0.2.8)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\grace\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.14.0->mlflow) (0.4.8)
Using cached mlflow-3.14.0-py3-none-any.whl (12.6 MB)
Using cached mlflow_skinny-3.14.0-py3-none-any.whl (3.5 MB)
Using cached mlflow_tracing-3.14.0-py3-none-any.whl (1.7 MB)
Using cached flask_cors-6.0.5-py3-none-any.whl (16 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Using cached databricks_sdk-0.119.0-py3-none-any.whl (948 kB)
Using cached fastapi-0.138.1-py3-none-any.whl (129 kB)
Using cached opentelemetry_sdk-1.43.0-py3-none-any.whl (178 kB)
Using cached google_auth-2.55.1-py3-none-any.whl (252 kB)
Installing collected packages: graphene, opentelemetry-sdk, google-auth, Flask-CORS, fastapi, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
Successfully installed Flask-CORS-6.0.5 databricks-sdk-0.119.0 fastapi-0.138.1 google-auth-2.55.1 graphene-3.4.3 mlflow-3.14.0 mlflow-skinny-3.14.0 mlflow-tracing-3.14.0 opentelemetry-sdk-1.43.0

In [7]:
import mlflow
import numpy as np
import pickle
from sklearn.metrics import accuracy_score, f1_score

mlflow.set_experiment("Evaluasi_Model_PKL")


X_test = np.load("X_test2.npy")
y_test = np.load("y_test2.npy")

if len(X_test.shape) > 2:
    X_test = X_test.reshape(X_test.shape[0], -1)
    
params = {
    "max_depth": 5,
    "learning_rate": 0.1,
    "n_estimators": 100,
    "random_state": 42
}

with open("model_stress2.pkl", "rb") as f:
    model = pickle.load(f)


with mlflow.start_run() as run:
    mlflow.log_params(params)
    mdel_info = mlflow.sklearn.log_model(
    model, 
    "model", 
    skops_trusted_types=["xgboost.core.Booster", "xgboost.sklearn.XGBClassifier"]
)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    mlflow.log_metric("accuracy", acc)
    mlflow.set_tag("Training info", "Evaluasi menggunakan data NPY dan model PKL")

    exp_id = run.info.experiment_id
   
df_runs = mlflow.search_runs(experiment_ids=[exp_id])
display(df_runs)

print("\nKolom yang tersedia di MLflow search_runs:")
print(df_runs.columns.tolist())

loaded_model = mlflow.sklearn.load_model(mdel_info.model_uri)
print("\nModel berhasil di-load dari MLflow:")
print(loaded_model)

prediction = loaded_model.predict(X_test)
f1 = f1_score(prediction, y_test, average='macro')

print(f"\nF1 Score dari loaded_model: {f1}")

2026/06/27 20:41:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.accuracy,metrics.f1_macro,params.learning_rate,params.max_depth,params.n_estimators,params.random_state,tags.mlflow.user,tags.mlflow.source.name,tags.Training info,tags.mlflow.source.type,tags.mlflow.runName,tags.Tipe Model,tags.Status
0,9f0d92c6de4342f9b1e8de47355eecb4,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:41:57.215000+00:00,2026-06-27 13:42:07.172000+00:00,0.75401,NaN,0.1,5,100,42,grace,mlflow.ipynb,Evaluasi menggunakan data NPY dan model PKL,NOTEBOOK,gifted-skunk-224,None,None
1,d84145fa1a974eb0a4ebf429a2fbe99e,1,FAILED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:41:16.234000+00:00,2026-06-27 13:41:31.460000+00:00,NaN,NaN,None,None,None,None,grace,mlflow.ipynb,None,NOTEBOOK,loud-ape-773,None,None
2,0cd4aae856924b98aaa3188b00d48443,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:25:29.667000+00:00,2026-06-27 13:25:45.972000+00:00,0.75401,NaN,None,None,None,None,grace,mlflow.ipynb,Evaluasi menggunakan data NPY dan model PKL,NOTEBOOK,peaceful-penguin-311,None,None
3,eddc5d404a2340d5b45f70244787c4f8,1,FAILED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:22:45.206000+00:00,2026-06-27 13:22:52.236000+00:00,NaN,NaN,None,None,None,None,grace,mlflow.ipynb,None,NOTEBOOK,intelligent-gull-814,None,None
4,77ad6282f2d2483dada56d9d7ae8fc3e,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:13:35.812000+00:00,2026-06-27 13:13:36.078000+00:00,0.75401,0.756033,None,None,None,None,grace,mlflow.ipynb,None,NOTEBOOK,handsome-shark-396,Custom Model PKL,Evaluasi

Kolom yang tersedia di MLflow search_runs:
['run_id', 'experiment_id', 'status', 'artifact_uri', 'start_time', 'end_time', 'metrics.accuracy', 'metrics.f1_macro', 'params.learning_rate', 'params.max_depth', 'params.n_estimators', 'params.random_state', 'tags.mlflow.user', 'tags.mlflow.source.name', 'tags.Training info', 'tags.mlflow.source.type', 'tags.mlflow.runName', 'tags.Tipe Model', 'tags.Status']

Model berhasil di-load dari MLflow:
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

F1 Score dari loaded_model: 0.7560328713958765

In [8]:
import mlflow
import numpy as np
import pickle
from sklearn.metrics import accuracy_score, f1_score

mlflow.set_experiment("Evaluasi_Model_PKL")


X_test = np.load("X_test2.npy")
y_test = np.load("y_test2.npy")

if len(X_test.shape) > 2:
    X_test = X_test.reshape(X_test.shape[0], -1)
    
params = {
    "max_depth": 3,
    "learning_rate": 0.05,
    "n_estimators": 150,
    "random_state": 42
}

with open("model_stress2.pkl", "rb") as f:
    model = pickle.load(f)


with mlflow.start_run() as run:
    mlflow.log_params(params)
    mdel_info = mlflow.sklearn.log_model(
    model, 
    "model", 
    skops_trusted_types=["xgboost.core.Booster", "xgboost.sklearn.XGBClassifier"]
)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    mlflow.log_metric("accuracy", acc)
    mlflow.set_tag("Training info", "Evaluasi menggunakan data NPY dan model PKL")

    exp_id = run.info.experiment_id
   
df_runs = mlflow.search_runs(experiment_ids=[exp_id])
display(df_runs)

print("\nKolom yang tersedia di MLflow search_runs:")
print(df_runs.columns.tolist())

loaded_model = mlflow.sklearn.load_model(mdel_info.model_uri)
print("\nModel berhasil di-load dari MLflow:")
print(loaded_model)

prediction = loaded_model.predict(X_test)
f1 = f1_score(prediction, y_test, average='macro')

print(f"\nF1 Score dari loaded_model: {f1}")

2026/06/27 20:43:21 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.accuracy,metrics.f1_macro,params.learning_rate,params.max_depth,params.n_estimators,params.random_state,tags.mlflow.user,tags.mlflow.source.name,tags.Training info,tags.mlflow.source.type,tags.mlflow.runName,tags.Tipe Model,tags.Status
0,6edd9c95a00e40f8b2947f5865e9299b,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:43:21.566000+00:00,2026-06-27 13:43:31.687000+00:00,0.75401,NaN,0.05,3,150,42,grace,mlflow.ipynb,Evaluasi menggunakan data NPY dan model PKL,NOTEBOOK,sassy-snipe-275,None,None
1,9f0d92c6de4342f9b1e8de47355eecb4,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:41:57.215000+00:00,2026-06-27 13:42:07.172000+00:00,0.75401,NaN,0.1,5,100,42,grace,mlflow.ipynb,Evaluasi menggunakan data NPY dan model PKL,NOTEBOOK,gifted-skunk-224,None,None
2,d84145fa1a974eb0a4ebf429a2fbe99e,1,FAILED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:41:16.234000+00:00,2026-06-27 13:41:31.460000+00:00,NaN,NaN,None,None,None,None,grace,mlflow.ipynb,None,NOTEBOOK,loud-ape-773,None,None
3,0cd4aae856924b98aaa3188b00d48443,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:25:29.667000+00:00,2026-06-27 13:25:45.972000+00:00,0.75401,NaN,None,None,None,None,grace,mlflow.ipynb,Evaluasi menggunakan data NPY dan model PKL,NOTEBOOK,peaceful-penguin-311,None,None
4,eddc5d404a2340d5b45f70244787c4f8,1,FAILED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:22:45.206000+00:00,2026-06-27 13:22:52.236000+00:00,NaN,NaN,None,None,None,None,grace,mlflow.ipynb,None,NOTEBOOK,intelligent-gull-814,None,None
5,77ad6282f2d2483dada56d9d7ae8fc3e,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:13:35.812000+00:00,2026-06-27 13:13:36.078000+00:00,0.75401,0.756033,None,None,None,None,grace,mlflow.ipynb,None,NOTEBOOK,handsome-shark-396,Custom Model PKL,Evaluasi

Kolom yang tersedia di MLflow search_runs:
['run_id', 'experiment_id', 'status', 'artifact_uri', 'start_time', 'end_time', 'metrics.accuracy', 'metrics.f1_macro', 'params.learning_rate', 'params.max_depth', 'params.n_estimators', 'params.random_state', 'tags.mlflow.user', 'tags.mlflow.source.name', 'tags.Training info', 'tags.mlflow.source.type', 'tags.mlflow.runName', 'tags.Tipe Model', 'tags.Status']

Model berhasil di-load dari MLflow:
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

F1 Score dari loaded_model: 0.7560328713958765

In [9]:
import mlflow
import numpy as np
import pickle
from sklearn.metrics import accuracy_score, f1_score

mlflow.set_experiment("Evaluasi_Model_PKL")


X_test = np.load("X_test2.npy")
y_test = np.load("y_test2.npy")

if len(X_test.shape) > 2:
    X_test = X_test.reshape(X_test.shape[0], -1)
    
params = {
    "max_depth": 7,
    "learning_rate": 0.2,
    "n_estimators": 200,
    "random_state": 42
}

with open("model_stress2.pkl", "rb") as f:
    model = pickle.load(f)


with mlflow.start_run() as run:
    mlflow.log_params(params)
    mdel_info = mlflow.sklearn.log_model(
    model, 
    "model", 
    skops_trusted_types=["xgboost.core.Booster", "xgboost.sklearn.XGBClassifier"]
)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    mlflow.log_metric("accuracy", acc)
    mlflow.set_tag("Training info", "Evaluasi menggunakan data NPY dan model PKL")

    exp_id = run.info.experiment_id
   
df_runs = mlflow.search_runs(experiment_ids=[exp_id])
display(df_runs)

print("\nKolom yang tersedia di MLflow search_runs:")
print(df_runs.columns.tolist())

loaded_model = mlflow.sklearn.load_model(mdel_info.model_uri)
print("\nModel berhasil di-load dari MLflow:")
print(loaded_model)

prediction = loaded_model.predict(X_test)
f1 = f1_score(prediction, y_test, average='macro')

print(f"\nF1 Score dari loaded_model: {f1}")

2026/06/27 20:43:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.accuracy,metrics.f1_macro,params.learning_rate,params.max_depth,params.n_estimators,params.random_state,tags.mlflow.user,tags.mlflow.source.name,tags.Training info,tags.mlflow.source.type,tags.mlflow.runName,tags.Tipe Model,tags.Status
0,f4941ea809f94f6990dcfd973e888002,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:43:32.002000+00:00,2026-06-27 13:43:41.928000+00:00,0.75401,NaN,0.2,7,200,42,grace,mlflow.ipynb,Evaluasi menggunakan data NPY dan model PKL,NOTEBOOK,capricious-cub-903,None,None
1,6edd9c95a00e40f8b2947f5865e9299b,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:43:21.566000+00:00,2026-06-27 13:43:31.687000+00:00,0.75401,NaN,0.05,3,150,42,grace,mlflow.ipynb,Evaluasi menggunakan data NPY dan model PKL,NOTEBOOK,sassy-snipe-275,None,None
2,9f0d92c6de4342f9b1e8de47355eecb4,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:41:57.215000+00:00,2026-06-27 13:42:07.172000+00:00,0.75401,NaN,0.1,5,100,42,grace,mlflow.ipynb,Evaluasi menggunakan data NPY dan model PKL,NOTEBOOK,gifted-skunk-224,None,None
3,d84145fa1a974eb0a4ebf429a2fbe99e,1,FAILED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:41:16.234000+00:00,2026-06-27 13:41:31.460000+00:00,NaN,NaN,None,None,None,None,grace,mlflow.ipynb,None,NOTEBOOK,loud-ape-773,None,None
4,0cd4aae856924b98aaa3188b00d48443,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:25:29.667000+00:00,2026-06-27 13:25:45.972000+00:00,0.75401,NaN,None,None,None,None,grace,mlflow.ipynb,Evaluasi menggunakan data NPY dan model PKL,NOTEBOOK,peaceful-penguin-311,None,None
5,eddc5d404a2340d5b45f70244787c4f8,1,FAILED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:22:45.206000+00:00,2026-06-27 13:22:52.236000+00:00,NaN,NaN,None,None,None,None,grace,mlflow.ipynb,None,NOTEBOOK,intelligent-gull-814,None,None
6,77ad6282f2d2483dada56d9d7ae8fc3e,1,FINISHED,file:c:/Users/grace/OneDrive/Documents/ml-st-s...,2026-06-27 13:13:35.812000+00:00,2026-06-27 13:13:36.078000+00:00,0.75401,0.756033,None,None,None,None,grace,mlflow.ipynb,None,NOTEBOOK,handsome-shark-396,Custom Model PKL,Evaluasi

Kolom yang tersedia di MLflow search_runs:
['run_id', 'experiment_id', 'status', 'artifact_uri', 'start_time', 'end_time', 'metrics.accuracy', 'metrics.f1_macro', 'params.learning_rate', 'params.max_depth', 'params.n_estimators', 'params.random_state', 'tags.mlflow.user', 'tags.mlflow.source.name', 'tags.Training info', 'tags.mlflow.source.type', 'tags.mlflow.runName', 'tags.Tipe Model', 'tags.Status']

Model berhasil di-load dari MLflow:
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

F1 Score dari loaded_model: 0.7560328713958765